Repository peeranha/peeranha, pull requests merged in 2023-01, with the labels that each got.

#102 fixed bug when delete all replies user could not change post type to …
  contracts/libraries/PostLib.sol
  contracts/libraries/UserLib.sol
  test/contracts/test-forum-vote.js
  test/contracts/test-forum.js
Labels: bug, Fast

#99 Change reputation when moving posts to another community
  contracts/libraries/PostLib.sol
  contracts/libraries/UserLib.sol
  package.json
  test/contracts/test-1token.js
  test/contracts/test-change-postType-community.js
  test/contracts/test-dispatcher.js
  test/contracts/test-forum-permissions.js
  test/contracts/test-forum-vote.js
  test/contracts/test-forum.js
  test/contracts/test-local.js
  test/contracts/utils.js
Labels: bug

#101 Fix bot reply error (2+ replies)
  contracts/libraries/PostLib.sol
  package-lock.json
  package.json
  scripts/common-action.js
  scripts/force-import.js
  scripts/upgrade-content.js
  test/contracts/test-bot.js
Labels: bug, Fast

#92 Peer-565: separate community rights
  contracts/PeeranhaUser.sol
  test/contracts/test-energy.js
  test/contracts/test-forum-permissions.js
  test/contracts/test-forum.js
Labels: enhancement, Fast
